### ISSUE TITLE
Potential descrepancies between paper and code

### ISSUE THREAD

**Issue by ikostrikov** [fiorenza2/OffCon3#2]
Hi Philip,

Thanks for sharing this amazing repository and the paper!

The performance reported in the paper seems to outperform the author's original implementation and I was trying to incorporate the changes into my personal repository.

While looking at the code I've noticed that there is a difference in one of the hyper parameters defined in Table 1 and this code. In particular, in the table it says that the MLP has 2 hidden layers while in the code is seems to be set to 3: https://github.com/fiorenza2/OffCon3/blob/master/networks.py#L14

Please let me know if I missed something.

**Comment by fiorenza2** [comment]
Hi Ilya,

Great catch! Just looked at author's code too just to make sure and they have only 2 hidden layers; I will make it clear in the README and update the paper accordingly :)

I'll also rerun some experiments to see if the diff is actually down to these "superior" hyperparams.

**Comment by fiorenza2** [comment]
Hi Ilya,

Apologies for the delay in getting back; I've rerun some quick experiments with the 2 hidden layer MLPs and will include the comparison in the appendix for the updated report. Long story short is that in HalfCheetah the results are strikingly worse with 2 layers, but in Hopper SAC improves significantly to match TD3. Otherwise it's basically the same in the limit, with some environments having maybe faster convergence with the shallower networks.

I will make it clear that this implementation has the diff you outlined compared to the authors' code :)
